name: Analyze code

on:
  push:
    branches:
      - "dev"
    paths:
      - "src**"
      - "requirements.txt"
  pull_request:
    branches:
      - "dev"
      - "main"
    paths:
      - "src**"
      - "requirements.txt"

jobs:
  analyze:
    name: Analyze code
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: pylint --exit-zero $(git ls-files 'src/*.py')
